ARG VERSION
FROM nginmesh/nginx-dev:$VERSION
MAINTAINER Sehyo Chang "sehyo@nginx.com"

# this is coming from context which is from /build/context not root of the source
COPY ./test/config/nginx.conf /etc/nginx/nginx.conf
COPY ./test/config/conf.d/http.conf /etc/nginx/conf.d/http.conf
COPY ./test/config/conf.d/remote.conf /etc/nginx/conf.d/remote.conf
COPY ./test/services/http.js /test/http.js
COPY ./test/deploy.sh /test/deploy.sh
ADD nginx/nginx-linux/objs/ngx_http_collector_module.so /etc/nginx/modules
